# Generated by Django 4.0 on 2021-12-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_cover_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
