# Generated by Django 4.0 on 2022-01-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_body_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, default='Content', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(blank=True, default='User', null=True),
        ),
    ]
