# Generated by Django 4.0 on 2022-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_body_alter_post_title_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(default='Content', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(default='User'),
        ),
    ]
